server:
  port: 86

logging:
  level:
    root: info
mybatis-plus:
  global-config:
    banner: off
    db-config:
      table-prefix: tb_
      id-type: auto

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


spring:
  main:
    banner-mode: off
    log-startup-info: off
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/tmp?serverTimezone=UTC
#    username: root
#    password: 321321321
#    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/tmp #?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 321321321
  devtools:
    restart:
      exclude: static/**,public/**,config/application.yml
      #enabled: false
