server:
  port: 80

logging:
  level:
    root: info
mybatis-plus:
  global-config:
    banner: off
    db-config:
      table-prefix: tb_


spring:
  main:
    banner-mode: off
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/tmp?serverTimezone=UTC
#    username: root
#    password: 321321321
#    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/tmp?serverTimezone=UTC
      username: root
      password: 321321321