server:
  port: 80
logging:
  level:
    root: info
spring:
  main:
    banner-mode: off

  #1,创建封装类，封装以下数据
  #2，由spring加载数据到对象中，一定要spring加载这组信息
  #3，使用数据的时候，从spring中直接获取
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tmp
    username: root
    password: 321321321

country: china
province: beijing
city: beijing
area: haidian

party: true

birthday: 1949-10-01

user1:
  name: itacast
  age: 16

user2:
  name: itheima
  age: 16

a:
  b:
    c:
      d:
        e: 123

likes:
  - game
  - music
  - basketball
  - sleep

likes2: [game, music, basketball, sleep]

users:
  - name: zhansan
    age: 18
  - name: lisi
    age: 20

users3: [{name:zhangsan, age:16}, {name:lisi, age:16}]

users2:
  -
    name: zhansan
    age: 18
  -
    name: lisi
    age: 17

baseDir: /Users/dreamtank77
tempDir: ${baseDir}/temp

tempDir2: "${baseDir}/temp \t1 \t2 \t3"
