server:
  port: 80
logging:
  level:
    root: info
spring:
  main:
    banner-mode: off

country: china
province: beijing
city: beijing
area: haidian

party: true

birthday: 1949-10-01

user1:
  name: itacast
  age: 16

user2:
  name: itheima
  age: 16

a:
  b:
    c:
      d:
        e: 123

likes:
  - game
  - music
  - basketball
  - sleep

likes2: [game, music, basketball, sleep]

users:
  - name: zhansan
    age: 18
  - name: lisi
    age: 20

users3: [{name:zhangsan, age:16}, {name:lisi, age:16}]

users2:
  -
    name: zhansan
    age: 18
  -
    name: lisi
    age: 17

baseDir: /Users/dreamtank77/IdeaProjects/springboot2/springboot_02_base_quickstart/src/main/java/com/itheima

tempDir: ${baseDir}/temp

tempDir2: "${baseDir}/temp \t1 \t2 \t3"