server:
  port: 80
spring:
#  1。activemq
#  activemq:
#    broker-url: tcp://localhost:61616
#  jms:
#    template:
#      default-destination: itheima
#    pub-sub-domain: true

#  2。rabbitmq
  rabbitmq:
    host: localhost
    port: 5672