#应用环境--公共配置
#spring:
#  profiles:
#    active: dev
#    include: devMVC,devDB


spring:
  profiles:
    active: dev #@profile.active@
    group:
      "dev": devMVC,devDB
      "pro": proMVC,proDB
logging:
  group: #设置分组
    ebank: com.itheima.controller, com.itheima.service, com.itheima.dao
    iservice: com.alibaba
  level:
    #设置某个包的日志级别
    com.itheima.controller: debug
    #设置分组，对某个组设置日志级别
    ebank: warn
    root: info
  pattern:
    #console: "%d %clr(%5p) --- [%16t] %clr(%-40.40c){cyan} : %m %n"
    #console: "%d - %m %n"
  file:
    name: springboot.log
  logback:
    rollingpolicy:
      max-file-size: 1KB
      file-name-pattern: server.%d{yyyy-MM-dd}.%i.log