server:
  port: 80

test:
  prop: testValue
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/tmp?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 321321321
mybatis-plus:
  global-config:
    banner: off
    db-config:
      table-prefix: tb_
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

testcase:
  book:
    id: ${random.int}
    id2: ${random.int(10,15)}
    type: ${random.int(5,10)}
    name: 黑马${random.value}
    uuid: ${random.uuid}
    publishTime: ${random.long}
