#
#server:
#  port: 80
#test:
#  prop: testValue
##spring:
##  datasource:
##    druid:
##      driver-class-name: com.mysql.cj.jdbc.Driver
##      url: jdbc:mysql://localhost:3306/tmp?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
##      username: root
##      password: 321321321
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/tmp?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#    hikari:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      username: root
#      password: 321321321
#      #jdbc-url: jdbc:mysql://localhost:3306/tmp?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#
#    #type: com.alibaba.druid.pool.DruidDataSource
#
#mybatis-plus:
#  global-config:
#    banner: off
#    db-config:
#      table-prefix: tb_
#      id-type: auto
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#h2
server:
  port: 80
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE;
    hikari:
      #driver-class-name: org.h2.Driver
      username: sa
      password: 123456

mybatis-plus:
  global-config:
    banner: off
    db-config:
      table-prefix: tb_
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl